namespace: prod
deploy:
  name: nop-commerce
  replicas: 1
  port: 80
  image: nopcommerce
  tag: 5
  imagePullSecrets: regcred
  registry: bcfmhakan/
  resources:
    enabled: true
    requestCpu: 200m
    requestMemory: 300Mi
    limitCpu: 1700m
    limitMemory: 20000Mi
svc:
  enabled: true
  name: nop-commerce
  port: 80
hpa:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 30
    targetMemoryUtilizationPercentage: 30
probe:
  enabled: true
  failureThreshold: 1
  periodSeconds: 70
  timeoutSeconds: 50
  initialDelaySeconds: 60
  pathreadiness: /
  pathliveness: /
  port: 80
ingress:
  enabled: false
  hosts: 
    - nopcommerce.bestcloudfor.me
configmap:
  enabled: true
  name: nop-config
  mounth:
    enabled: true
    name: mounth-name
    workdir: /app/
    files: 
      - appsettings.json
